version: '3.8'
services:
client:
build: ./ client
ports:
- "3000:80"  # Host: Container
depends_on:
- server
environment:
- NODE_ENV=production

server:
build: ./ server
ports:
- "5000:5000"  # Host: Container
volumes:
- ./ server / data: /app/data  # Persist SQLite DB
environment:
- NODE_ENV=production