services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fairwayboss_server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://fairwayboss:vJ61vN9c1DAiPWB8@fairwaybosscluster.uujkm.mongodb.net/?retryWrites=true&w=majority&appName=FairwayBossCluster"
      SECRET_KEY: "your-secret-key"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fairwayboss_client
    ports:
      - "3000:80"
    depends_on:
      - server
